export const ProductList = [
  {
    id: 1,
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/u/n/p/-original-imagugptgsfbxauz.jpeg?q=70",
    imgCousins: [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/p/u/8/-original-imagugptptuacajg.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/c/p/-original-imagugptdmkvpwpm.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/f/r/2/-original-imagugptvr3dbzpb.jpeg?q=70",
    ],
    model: "vivo Y200 ",
    brand: "Vivo",
    price: 21999,
    color: "",
    space: "8 GB RAM | 128 GB ROM",
    camera: "64MP + 2MP | 16MP Front Camera",
    battery: "4800 mAh Battery",
    count: 1,
    isAdded: false,
    type: "Mobile",
    isTrending: true,
    description:
      "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box",
  },
  {
    id: 2,
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/k/g/j/t3x-5g-v2338-vivo-original-imahyyzaqhgwzfup.jpeg?q=70",
    model: "Vivo T3x 5G",
    brand: "Vivo",
    price: 23999,
    space: "12 GB RAM | 256 GB ROM",
    camera: "108MP + 13MP + 2MP | 50MP Front Camera",
    battery: "5000 mAh Battery",
    count: 1,
    isAdded: false,
    type: "Mobile",
    isTrending: false,
    description:
      "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box",
  },
  {
    id: 3,
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/s/y/narzo-60-5g-rmx3750-realme-original-imagrht2yzyc2jyj.jpeg?q=70",
    model: "realme Narzo 60 ",
    brand: "Realme",
    price: 17868,
    space: "8 GB RAM | 128 GB ROM",
    camera: "64MP Rear Camera",
    battery: "5000 mAh Battery",
    count: 1,
    isAdded: false,
    type: "Mobile",
    isTrending: true,
    description:
      "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box",
  },
  {
    id: 4,
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/2/z/4/-original-imagqxx2haehpjnf.jpeg?q=70",
    model: "realme 11 Pro ",
    brand: "Realme",
    price: 21999,
    space: "8 GB RAM | 128 GB ROM",
    camera: "100MP (OIS) + 2MP | 16MP Front Camera",
    battery: "5000 mAh Battery",
    count: 1,
    isAdded: false,
    type: "Mobile",
    isTrending: false,
    description:
      "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box",
  },
  {
    id: 5,
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/h/d/-original-imags487gaqqhcea.jpeg?q=70",
    model: "realme C53",
    brand: "Realme",
    price: 9999,
    space: "6 GB RAM | 64 GB ROM",
    camera: "108MP + 2MP | 8MP Front Camera",
    battery: "5000 mAh Battery",
    count: 1,
    isAdded: false,
    type: "Mobile",
    isTrending: true,
    description:
      "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box",
  },
  {
    id: 6,
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/4/h/e/-original-imagzjhwmsamexfk.jpeg?q=70",
    model: "vivo T2x ",
    brand: "Vivo",
    price: 12999,
    space: "6 GB RAM | 128 GB ROM",
    camera: "50MP + 2MP | 8MP Front Camera",
    battery: "5000 mAh Battery",
    count: 1,
    isAdded: false,
    type: "Mobile",
    isTrending: false,
    description:
      "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box",
  },
  {
    id: 7,
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/g/b/x/-original-imagtt4h4ptmxgwn.jpeg?q=70",
    model: "Vivo T2 Pro",
    brand: "Vivo",
    price: 19420,
    space: "8 GB RAM | 128 GB ROM",
    camera: "108MP Rear Camera",
    battery: "5000 mAh Battery",
    count: 1,
    isAdded: false,
    type: "Mobile",
    isTrending: false,
    description:
      "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box",
  },
  {
    id: 8,
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/t/f/2/y27-v2249-vivo-original-imahfmkqf5mrugjq.jpeg?q=70",
    model: "Vivo Y27",
    brand: "Vivo",
    price: 16770,
    space: "8 GB RAM | 128 GB ROM",
    camera: "50MP + 2MP | 8MP Front Camera",
    battery: "5000 mAh Battery",
    count: 1,
    isAdded: false,
    type: "Mobile",
    isTrending: false,
    description:
      "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box",
  },
];
